# arxivの学問領域の指定
subject: 'cat:cs.* OR cat:q-bio.*'

# 検索キーワード
keywords:
        pathology: 3
        neuropathology: 5
        neuropathologic: 5
        neuropathological: 5
        synuclein: 3
        α-synuclein: 3
        tau: 3
        multiple system atrophy: 5
        Alzheimer's disease: 5
        corticobasal degeneration: 5
        progressive supranuclear palsy: 5
        tauopathy: 5
        synucleinopathy: 5

# 通知の閾値
score_threshold: 4
